package brew

import (
	"bytes"
	"strings"
	"testing"
)

const sample = `# generated by brew bundle dump
tap "felixkratz/formulae", "https://github.com/FelixKratz/homebrew-formulae"

brew "openssl@3", link: true
brew "jq"
cask "ghostty", args: { no_quarantine: true }
mas "Xcode", id: 497799835
`

func TestParseRoundTripKeepsOptionsVerbatim(t *testing.T) {
	entries, err := Parse(strings.NewReader(sample))
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 5 {
		t.Fatalf("got %d entries: %+v", len(entries), entries)
	}
	if entries[0].Kind != "tap" || entries[0].Name != "felixkratz/formulae" || entries[0].Rest != `, "https://github.com/FelixKratz/homebrew-formulae"` {
		t.Fatalf("tap entry = %+v", entries[0])
	}
	if entries[1].Key() != "brew openssl@3" || entries[1].Rest != ", link: true" {
		t.Fatalf("brew entry = %+v", entries[1])
	}
	if entries[3].Line() != `cask "ghostty", args: { no_quarantine: true }` {
		t.Fatalf("Line() = %q", entries[3].Line())
	}
	var buf bytes.Buffer
	if err := Write(&buf, entries); err != nil {
		t.Fatal(err)
	}
	want := strings.Join([]string{
		`tap "felixkratz/formulae", "https://github.com/FelixKratz/homebrew-formulae"`,
		`brew "openssl@3", link: true`,
		`brew "jq"`,
		`cask "ghostty", args: { no_quarantine: true }`,
		`mas "Xcode", id: 497799835`,
	}, "\n") + "\n"
	if buf.String() != want {
		t.Fatalf("Write =\n%s\nwant\n%s", buf.String(), want)
	}
}

func TestParseRejectsGarbageWithLineNumber(t *testing.T) {
	_, err := Parse(strings.NewReader("brew \"jq\"\nthis is not a brewfile line\n"))
	if err == nil || !strings.Contains(err.Error(), "line 2") {
		t.Fatalf("want line 2 error, got %v", err)
	}
}

func e(kind, name string) Entry { return Entry{Kind: kind, Name: name} }

func TestCompare(t *testing.T) {
	committed := []Entry{e("tap", "a/b"), e("brew", "jq"), e("brew", "gone"), e("cask", "ghostty")}
	dump := []Entry{e("tap", "a/b"), e("brew", "jq"), e("brew", "new1"), e("cask", "ghostty"), e("cask", "new2")}
	d := Compare(committed, dump)
	if len(d.Added) != 2 || d.Added[0].Name != "new1" || d.Added[1].Name != "new2" {
		t.Fatalf("Added = %+v", d.Added)
	}
	if len(d.Removed) != 1 || d.Removed[0].Name != "gone" {
		t.Fatalf("Removed = %+v", d.Removed)
	}
}

func TestFilterKeepsCommittedOrderForRetainedRemovals(t *testing.T) {
	committed := []Entry{e("brew", "jq"), e("brew", "gone-keep"), e("brew", "gone-drop")}
	dump := []Entry{e("brew", "jq"), e("brew", "new-keep"), e("brew", "new-skip")}
	got := Filter(dump, committed,
		map[string]bool{"brew new-keep": true},
		map[string]bool{"brew gone-drop": true})
	var names []string
	for _, x := range got {
		names = append(names, x.Name)
	}
	if strings.Join(names, ",") != "jq,new-keep,gone-keep" {
		t.Fatalf("Filter = %v", names)
	}
}

func TestFilterWithNoCommittedKeepsOnlyChosen(t *testing.T) {
	dump := []Entry{e("brew", "a"), e("brew", "b")}
	got := Filter(dump, nil, map[string]bool{"brew b": true}, nil)
	if len(got) != 1 || got[0].Name != "b" {
		t.Fatalf("Filter = %+v", got)
	}
}

func TestTaps(t *testing.T) {
	got := Taps([]Entry{e("tap", "x/y"), e("brew", "jq"), e("tap", "z/w")})
	if strings.Join(got, ",") != "x/y,z/w" {
		t.Fatalf("Taps = %v", got)
	}
}

func TestExclude(t *testing.T) {
	got := Exclude([]Entry{e("brew", "jq"), e("go", "example.com/local/tool"), e("npm", "yarn")}, []string{"go example.com/local/tool"})
	if len(got) != 2 || got[1].Name != "yarn" {
		t.Fatalf("Exclude = %+v", got)
	}
	if n := len(Exclude(nil, []string{"x y"})); n != 0 {
		t.Fatalf("Exclude(nil) = %d", n)
	}
}
